### ISSUE TITLE
FSP Proposal Feedback

### ISSUE THREAD

**Issue by andywynkoop** [Frikster/Sloth#1]
Hey Dirk!
Nice job on the proposal so far, here are a few changes I'd like you to make: 
### Wiki Home Page
- [x] Add live link to site (can be dummy link for now)
- [x] Add relative links to all other design docs (bullet points)
- [x] Customize the welcome message (your site instead of 'AA Fullstack')

### MVP List
- [x] I think your core MVPs should be Channels, Live-Chat, Direct Messages, and Multi-user DMs;  I think the other things are good ideas too, but I don't want to hold you accountable for them. As soon as you finish the main features to completion, do them as bonuses.
- [x] Styling will be part of each MVP, you don't need to include the CSS bullet
- [x] Live chat is a little bit of extra setup, will likely take more than one day
### Schema 
- [x] Channel name should probably be unique and indexed
- [x] What kind of uniqueness constraints should be placed on direct messages? Can you have more than one direct message thread with the same person/people? 

### Backend Routes
- [x] I think it's fine to have messages un-nested. You also may want to just fetch the message data when you fetch a channel (maybe no 'get' routes at all)

**Comment by Frikster** [comment]
@andywynkoop 
For channel name I'm thinking they shouldn't be unique because although they should be unique to a workspace they need not be unique to the entire database. Two workspaces can have channels of the same name. Obviously [workspace_id, channel_name] should be unique but since I'm not adding workspaces for the fullstack project (only plan to add them after the program) I cant add this. It's fine to enforce uniqueness for now and have it easily changeable later? Also maybe I should create workspaces now to make sure they are set up properly for later? (can also be dummy workspaces)

**Comment by Frikster** [comment]
For DMs I'm thinking of DMs as functionally identical to channels except other users cannot visit them (i.e. private). And you can have two private channels with different names where each has the same 2 participants.

So the uniqueness constraint would just be on the channel name leading us back to the problem in my previous comment.

I think I should otherwise be able to use a selector and UserChannel[channel_id: id] to retrieve all the users of a channel and if direct_message_channel is true set a constraint on the list of users being unique.

**Comment by Frikster** [comment]
And finally, it's ok to call my Slack clone Evernote? I haven't actually decided on a name yet.

**Comment by Frikster** [comment]
Channel names unique for now - can easily change to make [workspace_id, channel name] unique in the future
direct messages = private channels. No need to do this constraint for now
